{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          {{- /*
          range 内で tpl で変数を遅延評価するためにコンテキストを変数に入れる
          */}}
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                {{- /*
                変数を遅延評価するので tpl に親コンテキストを渡す
                */}}
                name: {{ tpl .backend.service.name $ }}
                port:
                  number: {{ tpl .backend.port.number $ }}
          {{- end }}
{{- end }}
